//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.v3._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktor
    {
        public int D_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
        public string D_ad_soyad { get; set; }
        public Nullable<int> D_klinik_ID { get; set; }
        public string D_k_adi { get; set; }
        public string D_sifte { get; set; }
    }
}
