//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.v3._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eczane
    {
        public int İlac_ID { get; set; }
        public string İlac_adi { get; set; }
        public string İlac_ticari_ad { get; set; }
        public int İlac_stok { get; set; }
        public int İlac_klinik_ID { get; set; }
    }
}
