//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.v3._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hasta
    {
        public int H_ID { get; set; }
        public string H_tc { get; set; }
        public string H_adi { get; set; }
        public string H_s_adi { get; set; }
        public string H_cinsiyet { get; set; }
        public string H_d_yeri { get; set; }
        public string H_d_tarihi { get; set; }
        public string H_baba_adi { get; set; }
        public string H_anne_adi { get; set; }
        public string H_tel { get; set; }
        public string H_eposta { get; set; }
        public string H_sifre { get; set; }
        public Nullable<int> H_yatis_ID { get; set; }
        public string H_recete_ID { get; set; }
        public Nullable<int> H_randevu_ID { get; set; }
        public Nullable<int> D_ID { get; set; }
        public Nullable<int> H_nabiz { get; set; }
        public string H_randevu_tarih { get; set; }
        public Nullable<int> H_tedavi_durum { get; set; }
        public string H_tansiyon { get; set; }
        public Nullable<int> H_tahlil_ID { get; set; }
        public Nullable<int> H_ilac_ID { get; set; }
        public string H_tahlil_sonuc { get; set; }
        public string H_randevu_saat { get; set; }
        public string H_taburcu_tarih { get; set; }
        public string H_gecmis_randevu_tarih { get; set; }
    }
}
