//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.v3._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int P_ID { get; set; }
        public string P_tc { get; set; }
        public string P_adi { get; set; }
        public string P_s_adi { get; set; }
        public string P_anne_adi { get; set; }
        public string P_baba_adi { get; set; }
        public string P_d_yeri { get; set; }
        public Nullable<System.DateTime> P_d_tarihi { get; set; }
        public string P_sifre { get; set; }
        public string P_yetki { get; set; }
        public Nullable<int> P_birim_ID { get; set; }
        public Nullable<int> P_klinik_ID { get; set; }
        public string P_eposta { get; set; }
        public string P_tel { get; set; }
        public string p_cinsiyet { get; set; }
        public Nullable<int> P_izingun { get; set; }
    }
}
