//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.v3._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polikinlik
    {
        public int Polik_ID { get; set; }
        public Nullable<int> Polik_d_ID { get; set; }
        public string Polik_adi { get; set; }
    }
}
