//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.v3._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HastaneEntities : DbContext
    {
        public HastaneEntities()
            : base("name=HastaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doktor> Doktor { get; set; }
        public virtual DbSet<Eczane> Eczane { get; set; }
        public virtual DbSet<Laboratuvar> Laboratuvar { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Polikinlik> Polikinlik { get; set; }
        public virtual DbSet<Yatis> Yatis { get; set; }
        public virtual DbSet<Hasta> Hasta { get; set; }
    }
}
