//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.v3._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yatis
    {
        public int Yatis_ID { get; set; }
        public string Yatis_tarih { get; set; }
        public string H_tc { get; set; }
        public Nullable<int> Taburuc_durum { get; set; }
    }
}
